### ISSUE TITLE
Implement store based on Azure blob storage for profile store

### ISSUE THREAD

**Issue by Yshayy** [livecycle/preevy#102]
Implement a profile storage for azure blob storage.

Should be similar to other implementations:
- GS - https://github.com/livecycle/preevy/blob/main/packages/driver-gce/src/fs/index.ts
- S3 - https://github.com/livecycle/preevy/blob/main/packages/driver-lightsail/src/fs/index.ts

Registration is done here:
https://github.com/livecycle/preevy/blob/main/packages/cli/src/fs.ts

Url format should follow conventions of golang cloud sdk:
https://gocloud.dev/howto/blob/#azure

**Comment by hassansuhaib** [comment]
I want to work on this

**Comment by royra** [comment]
Done long ago #423
