### ISSUE TITLE
[BUG]: tunnel server can produce URLs that include invalid subdomain with >63 length

### ISSUE THREAD

**Issue by Yshayy** [livecycle/preevy#147]
### Bug description?

Subdomain is limited to 63 characters, we should trim to the characters to support valid URLs.
Implementation can be done in tunnel server or Preevy/compose tunnel agent.
In both cases, we should pay attention to the CLI functionality of predicting the URL for injecting env variables:
https://preevy.dev/recipes/service-discovery

We should also think if we want to truncate the entire subdomain url, or set a size limit for each fragment:
https://{service}-{[port]}-{env-id}-{client-id}

### Additional context
Current workaround: use the --id flag in up to create a shorter env identifier or use shorter branch names.

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by royra** [comment]
Fixed
