### ISSUE TITLE
[Improvement]:Update Package Scripts for Cross-Platform Compatibility

### ISSUE THREAD

**Issue by hassansuhaib** [livecycle/preevy#154]
### What feature?

Currently, some of the package scripts in our package.json files are not compatible with all operating systems. To ensure seamless development across different platforms, we need to update the scripts to be cross-platform compatible.

**Affected script:**
`clean` The current implementation uses rm -rf to remove directories, which is not compatible with Windows systems.

### Describe the solution you'd like

We should switch to a cross-platform solution like `rimraf`.

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by royra** [comment]
good idea!

[`packages/cli/package.json`](https://github.com/livecycle/preevy/blob/main/packages/cli/package.json#L89) uses [shx](https://www.npmjs.com/package/shx) which is a more generic solution AFAIK.

**Comment by roy9495** [comment]
Can I work on this issue?
