### ISSUE TITLE
`preevy logs --follow`

### ISSUE THREAD

**Issue by royra** [livecycle/preevy#165]
Missing feature in logs

**Comment by Light13008** [comment]
could you provide some details to where to look up, the file  for this issue ?

**Comment by royra** [comment]
Hi @Light13008 ,

Thank you for your interest!

This issue requires some understanding of the existing codebase. If you're not yet familiar with the project, I encourage you to start with some easier tasks. Once you're feeling up for it, please let us know by posting a short description of the suggested solution before opening a PR.

**Comment by roy9495** [comment]
Can I work on this issue?

**Comment by Light13008** [comment]
let @roy9495  work on this, as it will take me a long time to understand the project.

**Comment by royra** [comment]
fixed in #171
