### ISSUE TITLE
[DOCS]: Do we need A duplicate table of content?

### ISSUE THREAD

**Issue by Pradumnasaraf** [livecycle/preevy#172]
### What's wrong with the documentation?

 Do we need a duplicate table of content in README? It makes the page even longer

### Add screenshots

https://github.com/livecycle/preevy/assets/51878265/281bdf7f-e03a-46f9-8a42-23258d098985

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by royra** [comment]
We do if we want to be listed in [awesome](https://github.com/sindresorhus/awesome): [PR template](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md). See our [CI action](https://github.com/livecycle/preevy/actions/workflows/awesome-lint.yaml) running [awesome-lint](https://github.com/sindresorhus/awesome-lint).

**Comment by Pradumnasaraf** [comment]
Gotcha. Thank you.
