### ISSUE TITLE
[Feat]: Allow for adding environmental variables passed through the preevy up command

### ISSUE THREAD

**Issue by OriginalByteMe** [livecycle/preevy#221]
### What feature?

We should be able to securely pass in environmental variables through the preevy up command to the docker compose or docker run command, it is very hard atm to pass variables securely to the docker compose, as I would not want to for instance commit my aws access keys to my docker compose file on github.

### Describe the solution you'd like

Allow for either arguments to pass env variables through the preevy up command, either that or allow for custom docker run commands to allow us to manually set up certain dependencies and variables. 

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by Yshayy** [comment]
Hey @OriginalByteMe,
Thanks for reporting the issue.

Preevy uses docker compose under the hood, it's possible to pass the variables you want when creating the process. (or other variables if exported)
https://docs.docker.com/compose/environment-variables/set-environment-variables/

For example:

```MESSAGE="hello world" preevy up```

```
docker-compose.yaml
----
service:
    ....
    environment:
    - MESSAGE
# or using interpolation
service2:
    ...
    environment:
    - MY_VAR=${MESSAGE}

```
Interpolation is also useful for using the env variable in different context (like labels, git source, etc...).

It's also possible to use `.env` file and encrypt it using a tool like sops (https://github.com/getsops/sops) so it can be safely committed to the repo if desired. (maybe in the future, it can be integrated to Preevy as an optional plugin)
