### ISSUE TITLE
Allow copying the profile to a different storage

### ISSUE THREAD

**Issue by royra** [livecycle/preevy#231]
Use case: After creating a profile using `preevy init` and storing it locally, one would want to use the same profile on their CI pipeline. Currently they would have to recreate the profile and specify a sharable storage type (AWS S3 or GCS). This will create a new tunneling key and force them to re-specify the driver options. It would be helpful to have a command which copies the existing profile to another storage type.

Suggested UX:

`preevy profile cp [SOURCE_ALIAS] TARGET [--target-alias=NEW_ALIAS]`

* `SOURCE_ALIAS` is optional and defaults to the current profile
* `TARGET` is either the storage type `local`, `s3`, `gs` as denoted in the profile URL scheme, or a full URL, e.g, `s3://preevy-123456789-myprofile?region=eu-central-1`.
* `--target-alias` is optional and has a sane default, e.g, `${oldAlias}-${proto}-${profileId}`

If the `TARGET` arg is not a full URL, show interactive prompts to choose the storage driver options, e.g, region, bucket name. Otherwise the command can complete non-interactively.

Once the profile is copied:
* Print the new profile alias
* Switch the current profile to the newly created

**Comment by Yshayy** [comment]
Looks good.
I have a concern that having the profile stored in several places can cause a configuration drift so I think we should make the default behavior in-place listing update.

If the user doesn't provide alias, we can do in-place listing update. 
Also, the source alias might not be needed as we already have --profile flag. 

Lastly, 'upload' might be a better fit then 'cp' - although it's less accurate, it represents the case of moving a profile to the cloud, and it can help communicate the case in docs. Not sure about it...

So overall:
preevy profile upload <target-url> [optional-alias]

WDTY?

**Comment by royra** [comment]
> Looks good. I have a concern that having the profile stored in several places can cause a configuration drift so I think we should make the default behavior in-place listing update.

Does "in-place listing update" mean we update the local state to remove the reference to the old profile? It will not delete the actual profile. If the source is remote any CI flows using the old URL will still work.

> Also, the source alias might not be needed as we already have --profile flag.

`--profile` exists in the "operative" commands like `up`, `down`, `ls`, but doesn't exist in the `profile` topic, except for `profile use` where it makes sense.

`--profile` makes sense when the `upload` command name, less so when using `cp`.

> Lastly, 'upload' might be a better fit then 'cp' - although it's less accurate, it represents the case of moving a profile to the cloud, and it can help communicate the case in docs. Not sure about it...

There is a case where the target is `local`, and `upload` doesn't make sense. it's also weird if the source is not `local`, because then we're "downloading" before "uploading".

**Comment by Yshayy** [comment]
Yes, in-place update means we just modify the listing.
It's true that the profile current store it's not deleted, but that's also the behavior of `profile rm` atm. 
If the desired behavior is deletion, we can add a flag. (or the other way around, is we're already allowing the user to create a new alias)

AFAIK `profile config view/update`, `profile current` accept and respect the --profile flag. (--profile is more like a global flag)

There's probably a better command name than `upload` but the common case we're aiming for is migrating a local profile to the cloud, so the question is whether we have a name that can be more specific to the use-case but still accurate. (I thought about `clone` or `sync`, but their semantics have additional meanings)

**Comment by Yshayy** [comment]
Another option is to have `copy` as a 'low level' command, and `migrate` as a command alias that does the full operation of copying, updating alias, and removing old profile (if desired/possible).
The problem with `migrate` is that we might use it in different context in the future, so I like the option of reserving it.
