### ISSUE TITLE
[Bug]: Recreating a profile with the same alias cause an error if local profile was created in the past 

### ISSUE THREAD

**Issue by Yshayy** [livecycle/preevy#240]
### What feature?

Currently, it can be difficult to perform the following:
preevy init
preevy profile rm default
preevy init
The reason is that Preevy still save the local files of the profile under local://{alias}
This can be solved in two ways:
1. Create local profile under local://{thumbprint} by default instead of local://{alias}
2. Change profile rm to be more aggressive on local profiles, or add a flag -purge

I think the first option might be more simple and straightforward.

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by royra** [comment]
workaround at #293
