### ISSUE TITLE
Tunnel URLs output can be trimmed in terminal 

### ISSUE THREAD

**Issue by Yshayy** [livecycle/preevy#30]
In narrow terminals, preview environments can be trimmed, which result in broken links (when clicking or copying):
![image](https://user-images.githubusercontent.com/1076078/226703853-b71c1ea0-9ccf-4469-bd4a-d863319122a4.png)

**Comment by royra** [comment]
there's an existing `--no-truncate` opt that solves exactly that

**Comment by Yshayy** [comment]
Maybe it should be the default behavior?

**Comment by Yshayy** [comment]
Due to the fact that these links are still clickable, but broken
