### ISSUE TITLE
bug showing logs

### ISSUE THREAD

**Issue by eliyabar** [livecycle/preevy#31]
using the CLI to show logs show no prompt.
after executing up command, trying to show logs with a wrong service name does nothing.

Steps to reproduce:
* preevy up
* preevy logs any-text-you-want
* nothing happens, no error, no logs.

using debug level shows that socket is closed.

![image](https://user-images.githubusercontent.com/13337543/226863109-153aa174-617d-46e5-baaa-b96cee8d92f4.png)

* if there is no env up or after 'preevy down' command, the output is ok (  Error: No machine found for envId wekan-master)

**Comment by eliyabar** [comment]
the env name is wekan-master as shown in the debug and as i got when using the ls command.
'test' is basically any string, except the actual service name (which outputs the log for the service).

**Comment by royra** [comment]
need to error if the specified service doesn't exist. also - consider renaming/aliasing the `urls` command to `ps`.
