### ISSUE TITLE
[Bug]: Add timeout for send telemetry

### ISSUE THREAD

**Issue by Yshayy** [livecycle/preevy#333]
### What happened?

If telemetry sending is stuck or slow due to networking issues, the CLI is stuck

### Add screenshots

-

### Steps to reproduce the behavior

-

### Expected behavior

-

### What OS are you seeing the problem on?

MacOS

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by royra** [comment]
fixed in [24cac97786b63b052a2e5d6a8dc6d0ec4a648ef1](https://github.com/livecycle/preevy/commit/24cac97786b63b052a2e5d6a8dc6d0ec4a648ef1)
