### ISSUE TITLE
global flags not shown on --help

### ISSUE THREAD

**Issue by royra** [livecycle/preevy#34]
`preevy --help` should show all global flags (e.g, `--debug`)

**Comment by Abhi5Pande** [comment]
Can I work on this?

**Comment by sameerkali** [comment]
can someone explain what's going on here

**Comment by royra** [comment]
Assigning @Abhi5Pande since they were first.

Oclif's notion of "global flags" [attaches flags to specific commands](https://oclif.io/docs/global_flags), so this may prove trickier than it seems. If you need to make compatibility breaking-changes LMK. You're invited discuss this further [on our Slack](https://join.slack.com/t/preevyusers/shared_invite/zt-1shi7t2dy-~glGUC5pWCtGrH19bKNXrQ).

**Comment by royra** [comment]
@Abhi5Pande any progress?

**Comment by Abhi5Pande** [comment]
Yes @royra , experimenting with custom help class and figuring out how we can get the list of global flags
