### ISSUE TITLE
[Bug]: SyntaxError: Unexpected identifier 'assert'

### ISSUE THREAD

**Issue by ShivamB25** [livecycle/preevy#492]
### What happened?

When running the command npx preevy init, I encountered the following error:
SyntaxError: Unexpected identifier 'assert'

### Add screenshots

<img width="1195" alt="image" src="https://github.com/livecycle/preevy/assets/104637569/7699cb1b-2f6a-4e0b-a274-45ed4a02c0cb">

### Steps to reproduce the behavior

1. Open a terminal or command prompt.
2. Run the command `npx preevy init`.
3. The error `SyntaxError: Unexpected identifier 'assert'` is displayed.
4. Run the command `preevy init`.
5. The same error `SyntaxError: Unexpected identifier 'assert'` is displayed.

### Expected behavior

 expected the Preevy project initialization process to start without any errors. However, instead of the expected behavior, I encountered the `SyntaxError: Unexpected identifier 'assert'` error.[1]

### What OS are you seeing the problem on?

MacOS

### Additional context

while installing i received this:
```
npm install -g preevy
⠼
⠦
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated @aws-sdk/util-waiter@3.374.0: This package has moved to @smithy/util-waiter

added 766 packages in 2m```

nodejs version:
node -v
v22.1.0

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by royra** [comment]
Hi @ShivamB25

- Can you try with Node.js v18.19.1? You can use [nvm](https://github.com/nvm-sh/nvm) to easily switch between Node.js versions.
- If this doesn't work, can you please run `DEBUG='*' preevy init --debug` and copy the full trace details?

**Comment by royra** [comment]
Looks related to the latest changes in Node.js 22: https://github.com/nodejs/node/pull/52104

**Comment by ShivamB25** [comment]
thank you
