### ISSUE TITLE
README - aws login

### ISSUE THREAD

**Issue by eliyabar** [livecycle/preevy#74]
The main README says:
``
In AWS, it could be by using aws login or aws configure
``

the [AWS cli ](https://awscli.amazonaws.com/v2/documentation/api/latest/index.html)doesn't contain any login command.

what am i missing?

**Comment by Yshayy** [comment]
I think it's a mistake, it should be only aws configure

**Comment by hassansuhaib** [comment]
@eliyabar Please close this issue as it has been resolved.
