### ISSUE TITLE
feat: add new issue templates

### ISSUE THREAD

**Issue by priyankarpal** [livecycle/preevy#88]
currently, we have only two issue templates we can add a few templates such as style, docs etc. 

- we need to use the `.yml` format issue template like these.
![image](https://github.com/livecycle/preevy/assets/88102392/e1bec79c-36f3-49d0-a963-67a7a9c97fa8)

## features if we use the `.yml` format 
- we can add multiple textboxes, checkboxes, tags etc. 
![image](https://github.com/livecycle/preevy/assets/88102392/cc58c87e-6e1e-46ff-ace9-22d582290d0e)

### I want to work on this issue

**Comment by royra** [comment]
@priyankarpal sounds great! Feel free to open a PR, and we'll continue the discussion there

**Comment by priyankarpal** [comment]
> @priyankarpal sounds great! Feel free to open a PR, and we'll continue the discussion there

so sorry I was busy with my work I'm creating the PR now

**Comment by Yshayy** [comment]
@priyankarpal thanks for the contribution
